name: "foo"
description: "bar"

runs:
  runs-on: ubuntu-latest
  steps:
    - name: Bump version and push tag
      run: |
        chmod +x ./scripts/test.sh
        ./scripts/test.sh
      shell: bash
